package Database;

public enum ControllerState {
	INIT,
	INSERT_EXERCISE,
	INSERT_EXERCISE_INTO_WORKOUT,
	INSERT_EQUIPMENT,
	INSERT_EXERCISE_GROUP,
	CREATE_WORKOUT,
	GET_EXCERSICE_IN_GROUP,
	GET_N_LAST_WORKOUTS,
	INSERT_EXERCISE_WITH_EQUIPMENT

}
