package Database;

public enum ControllerState {
	//Enums are named accourding to the activity the user is currently in. E.g. INSERT_EXERCISE_INTO_GROUP, as an imperative
	INIT,
	INSERT_EXERCISE,
	INSERT_EXERCISE_INTO_WORKOUT,
	INSERT_EQUIPMENT,
	INSERT_EXERCISE_GROUP,
	INSERT_GROUP_NUMBER_FOR_VIEWING_EXERCISES,
	INSERT_NUMBER_FOR_VIEWING_LATEST_WORKOUTS,
	CREATE_WORKOUT,
	GET_EXCERSICE_IN_GROUP,
	GET_N_LAST_WORKOUTS,
	INSERT_EXERCISE_WITH_EQUIPMENT
}
